name: powerbook_cli
description: A simple command-line application.
version: 0.0.1
homepage: https://github.com/powerd6/powerbook-cli
license: MIT

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies: 
  powerbook: ^0.0.2

dev_dependencies:
  lints: ^1.0.0
